// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CodechatSession struct {
	ID                     int32
	SessionID              pgtype.UUID
	CodechatInstance       string
	CodechatInstcanceToken string
	ChatwootToken          string
	ChatwootAccountID      int32
	ChatwootInboxID        int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}
