// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO codechat_session (
    session_id,
    codechat_instance,
    codechat_instcance_token,
    chatwoot_token,
    chatwoot_account_id,
    chatwoot_inbox_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, session_id, codechat_instance, codechat_instcance_token, chatwoot_token, chatwoot_account_id, chatwoot_inbox_id, created_at, updated_at
`

type CreateSessionParams struct {
	SessionID              pgtype.UUID
	CodechatInstance       string
	CodechatInstcanceToken string
	ChatwootToken          string
	ChatwootAccountID      int32
	ChatwootInboxID        int32
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CodechatSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionID,
		arg.CodechatInstance,
		arg.CodechatInstcanceToken,
		arg.ChatwootToken,
		arg.ChatwootAccountID,
		arg.ChatwootInboxID,
	)
	var i CodechatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CodechatInstance,
		&i.CodechatInstcanceToken,
		&i.ChatwootToken,
		&i.ChatwootAccountID,
		&i.ChatwootInboxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM codechat_session
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionBySessionId = `-- name: DeleteSessionBySessionId :exec
DELETE FROM codechat_session
WHERE session_id = $1
`

func (q *Queries) DeleteSessionBySessionId(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionBySessionId, sessionID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, session_id, codechat_instance, codechat_instcance_token, chatwoot_token, chatwoot_account_id, chatwoot_inbox_id, created_at, updated_at FROM codechat_session
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int32) (CodechatSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i CodechatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CodechatInstance,
		&i.CodechatInstcanceToken,
		&i.ChatwootToken,
		&i.ChatwootAccountID,
		&i.ChatwootInboxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionBySessionId = `-- name: GetSessionBySessionId :one
SELECT id, session_id, codechat_instance, codechat_instcance_token, chatwoot_token, chatwoot_account_id, chatwoot_inbox_id, created_at, updated_at FROM codechat_session
WHERE session_id = $1 LIMIT 1
`

func (q *Queries) GetSessionBySessionId(ctx context.Context, sessionID pgtype.UUID) (CodechatSession, error) {
	row := q.db.QueryRow(ctx, getSessionBySessionId, sessionID)
	var i CodechatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CodechatInstance,
		&i.CodechatInstcanceToken,
		&i.ChatwootToken,
		&i.ChatwootAccountID,
		&i.ChatwootInboxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, session_id, codechat_instance, codechat_instcance_token, chatwoot_token, chatwoot_account_id, chatwoot_inbox_id, created_at, updated_at FROM codechat_session
`

func (q *Queries) ListSessions(ctx context.Context) ([]CodechatSession, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodechatSession
	for rows.Next() {
		var i CodechatSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CodechatInstance,
			&i.CodechatInstcanceToken,
			&i.ChatwootToken,
			&i.ChatwootAccountID,
			&i.ChatwootInboxID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE codechat_session
  set session_id = $2,
  codechat_instance = $3,
  codechat_instcance_token = $4,
  chatwoot_token = $5,
  chatwoot_account_id = $6,
  chatwoot_inbox_id = $7
WHERE id =  $1
`

type UpdateSessionParams struct {
	ID                     int32
	SessionID              pgtype.UUID
	CodechatInstance       string
	CodechatInstcanceToken string
	ChatwootToken          string
	ChatwootAccountID      int32
	ChatwootInboxID        int32
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.SessionID,
		arg.CodechatInstance,
		arg.CodechatInstcanceToken,
		arg.ChatwootToken,
		arg.ChatwootAccountID,
		arg.ChatwootInboxID,
	)
	return err
}
